import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useState } from "react";
import NavBar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Link href="/portfolio">portfolio</Link>
          <Link href="/dashboard/analytics">Analytics</Link>
          <Link href="/dashboard/settings/profile">Profile</Link>
          <Link href="/dashboard/settings/password">Password</Link>
        </div>

        <NavBar />

        {children}
      </body>
    </html>
  );
}
